export const PAGE_LINKS: { label: string; url: string }[] = [
  { label: "Dashboard",        url: "/dashboard" },
  { label: "Events",           url: "/events" },
  { label: "Events – Duelle",  url: "/events?tab=duels" },
  { label: "Leaderboard",      url: "/leaderboard" },
  { label: "Shop",             url: "/shop" },
  { label: "Profil",           url: "/profile" },
  { label: "Level-Up-League",  url: "/lul" },
  { label: "Punkte-System",    url: "/points" },
  { label: "Quests",           url: "/quests" },
  { label: "Clip des Monats",  url: "/clip-des-monats" },
  { label: "Clip des Jahres",  url: "/clip-des-jahres" },
  { label: "Clip-Galerie",     url: "/clip-galerie" },
  { label: "Gameserver",       url: "/servers" },
  { label: "Spendenpool",      url: "/donations" },
  { label: "Feed",             url: "/feed" },
];
