// Kuratierte Icon-Auswahl für Event-Reihen und Squads (aus dem Casual-Game-UI-Set).
// Bilder: public/icons/picto/<id>.png (weiße Glyphen, werden per CSS-Maske eingefärbt).

export type PictoCategory = { name: string; icons: { id: string; label: string; keywords: string }[] };

export const PICTO_CATEGORIES: PictoCategory[] = [
  {
    name: "Kampf",
    icons: [
      { id: "sword", label: "Schwert", keywords: "sword klinge" },
      { id: "battle", label: "Schlacht", keywords: "battle gekreuzte schwerter" },
      { id: "fight", label: "Kampf", keywords: "fight schild schwert" },
      { id: "axe", label: "Axt", keywords: "axe" },
      { id: "hatchet", label: "Beil", keywords: "hatchet" },
      { id: "shuriken", label: "Wurfstern", keywords: "shuriken ninja" },
      { id: "gun", label: "Pistole", keywords: "gun waffe" },
      { id: "missile", label: "Rakete", keywords: "missile" },
      { id: "boom", label: "Explosion", keywords: "boom bombe" },
      { id: "magic-bomb", label: "Bombe", keywords: "bomb" },
      { id: "shield", label: "Schild", keywords: "shield" },
      { id: "armor", label: "Rüstung", keywords: "armor" },
      { id: "helmet", label: "Helm", keywords: "helmet" },
      { id: "viking-helmet", label: "Wikingerhelm", keywords: "viking helmet" },
      { id: "glove", label: "Handschuh", keywords: "glove" },
      { id: "fist", label: "Faust", keywords: "fist" },
      { id: "attack", label: "Angriff", keywords: "attack" },
      { id: "damage", label: "Schaden", keywords: "damage" },
      { id: "critical", label: "Volltreffer", keywords: "critical crit" },
      { id: "defense", label: "Verteidigung", keywords: "defense" },
      { id: "skull", label: "Totenkopf", keywords: "skull tod" },
      { id: "assassin", label: "Assassine", keywords: "assassin" },
      { id: "boss", label: "Boss", keywords: "boss gegner" },
      { id: "target", label: "Fadenkreuz", keywords: "target ziel" },
      { id: "tank", label: "Panzer", keywords: "tank" },
      { id: "anvil", label: "Amboss", keywords: "anvil schmied" },
      { id: "hammer", label: "Hammer", keywords: "hammer" },
      { id: "kinght", label: "Ritter", keywords: "knight" },
    ],
  },
  {
    name: "Sport & Rennen",
    icons: [
      { id: "ball", label: "Ball", keywords: "ball" },
      { id: "ball-attack", label: "Ballwurf", keywords: "ball attack" },
      { id: "airplane", label: "Flugzeug", keywords: "airplane flug" },
      { id: "rocket", label: "Rakete", keywords: "rocket weltraum" },
      { id: "boot-fly", label: "Flügelschuh", keywords: "boot fly speed" },
      { id: "shoes", label: "Schuh", keywords: "shoes lauf" },
      { id: "speed", label: "Tempo", keywords: "speed schnell" },
      { id: "stopwatch", label: "Stoppuhr", keywords: "stopwatch zeit" },
      { id: "timer", label: "Timer", keywords: "timer zeit" },
      { id: "flag-0", label: "Flagge", keywords: "flag" },
      { id: "flag-1", label: "Wimpel", keywords: "flag" },
      { id: "goal", label: "Ziel", keywords: "goal" },
      { id: "health", label: "Kraft", keywords: "muskel health training" },
      { id: "training", label: "Training", keywords: "training" },
      { id: "horseshoes", label: "Hufeisen", keywords: "horseshoe glück" },
      { id: "compass", label: "Kompass", keywords: "compass" },
      { id: "map-0", label: "Karte", keywords: "map" },
      { id: "wing", label: "Flügel", keywords: "wing" },
      { id: "thunder", label: "Blitz", keywords: "thunder energy" },
      { id: "siren", label: "Sirene", keywords: "siren polizei" },
    ],
  },
  {
    name: "Belohnung",
    icons: [
      { id: "trophy-0", label: "Pokal", keywords: "trophy" },
      { id: "trophy-1", label: "Pokal Stern", keywords: "trophy" },
      { id: "crown", label: "Krone", keywords: "crown" },
      { id: "coin-crown", label: "Münze Krone", keywords: "coin" },
      { id: "coin-star", label: "Münze Stern", keywords: "coin" },
      { id: "medal-0", label: "Medaille", keywords: "medal" },
      { id: "medal-1", label: "Medaille Band", keywords: "medal" },
      { id: "award", label: "Auszeichnung", keywords: "award" },
      { id: "achieve", label: "Erfolg", keywords: "achieve" },
      { id: "laurel", label: "Lorbeer", keywords: "laurel" },
      { id: "star", label: "Stern", keywords: "star" },
      { id: "leaderboard", label: "Podest", keywords: "leaderboard rang" },
      { id: "ranking", label: "Rangliste", keywords: "ranking" },
      { id: "gem-diamond", label: "Diamant", keywords: "gem diamond" },
      { id: "gem-hexagon", label: "Edelstein Sechseck", keywords: "gem" },
      { id: "gem-rhombus", label: "Edelstein Raute", keywords: "gem" },
      { id: "gem-triangle", label: "Edelstein Dreieck", keywords: "gem" },
      { id: "gift", label: "Geschenk", keywords: "gift" },
      { id: "chest-0", label: "Truhe", keywords: "chest" },
      { id: "chest-1", label: "Schatztruhe", keywords: "chest" },
      { id: "moneybag", label: "Geldsack", keywords: "money" },
      { id: "piggy", label: "Sparschwein", keywords: "piggy" },
      { id: "ticket", label: "Ticket", keywords: "ticket" },
      { id: "key-crown", label: "Kronenschlüssel", keywords: "key" },
      { id: "crystal", label: "Kristall", keywords: "crystal" },
    ],
  },
  {
    name: "Natur & Tiere",
    icons: [
      { id: "fire", label: "Feuer", keywords: "fire flamme" },
      { id: "water", label: "Wasser", keywords: "water" },
      { id: "sun", label: "Sonne", keywords: "sun" },
      { id: "moon", label: "Mond", keywords: "moon" },
      { id: "leaf", label: "Blatt", keywords: "leaf" },
      { id: "tree", label: "Baum", keywords: "tree" },
      { id: "tree-pine", label: "Tanne", keywords: "pine" },
      { id: "flower", label: "Blume", keywords: "flower" },
      { id: "cactus", label: "Kaktus", keywords: "cactus" },
      { id: "mushroom", label: "Pilz", keywords: "mushroom" },
      { id: "clover", label: "Kleeblatt", keywords: "clover" },
      { id: "feather", label: "Feder", keywords: "feather" },
      { id: "bone", label: "Knochen", keywords: "bone" },
      { id: "fish", label: "Fisch", keywords: "fish" },
      { id: "fish-bone", label: "Gräte", keywords: "fish bone" },
      { id: "paw", label: "Pfote", keywords: "paw" },
      { id: "pet", label: "Haustier", keywords: "pet" },
      { id: "pumkin", label: "Kürbis", keywords: "pumpkin halloween" },
      { id: "planet", label: "Planet", keywords: "planet weltraum" },
      { id: "blackhole", label: "Schwarzes Loch", keywords: "blackhole" },
      { id: "bat", label: "Fledermaus", keywords: "bat" },
      { id: "meat", label: "Fleisch", keywords: "meat" },
    ],
  },
  {
    name: "Fantasy & Magie",
    icons: [
      { id: "wand-1", label: "Zauberstab Stern", keywords: "wand" },
      { id: "magic", label: "Magie", keywords: "magic" },
      { id: "magic-ball", label: "Zauberkugel", keywords: "magic ball" },
      { id: "magic-drop", label: "Zaubertropfen", keywords: "magic drop" },
      { id: "magic-square", label: "Sechsstern", keywords: "magic" },
      { id: "rune", label: "Rune", keywords: "rune" },
      { id: "potion", label: "Trank", keywords: "potion" },
      { id: "posion", label: "Gift", keywords: "poison" },
      { id: "witchhat", label: "Hexenhut", keywords: "witch" },
      { id: "ankh", label: "Ankh", keywords: "ankh" },
      { id: "yinyang", label: "Yin Yang", keywords: "yinyang" },
      { id: "castle", label: "Burg", keywords: "castle" },
      { id: "tower", label: "Turm", keywords: "tower" },
      { id: "scroll", label: "Schriftrolle", keywords: "scroll" },
      { id: "book-0", label: "Buch", keywords: "book" },
      { id: "candle", label: "Kerze", keywords: "candle" },
      { id: "mana", label: "Mana", keywords: "mana" },
      { id: "priest", label: "Priester", keywords: "priest" },
      { id: "mask", label: "Maske", keywords: "mask" },
      { id: "angel", label: "Engel", keywords: "angel" },
      { id: "eyeball", label: "Auge", keywords: "eye" },
    ],
  },
  {
    name: "Spiel & Community",
    icons: [
      { id: "game", label: "Controller", keywords: "game controller" },
      { id: "joystick", label: "Joystick", keywords: "joystick arcade" },
      { id: "dice", label: "Würfel", keywords: "dice" },
      { id: "card", label: "Karten", keywords: "card" },
      { id: "puzzle", label: "Puzzle", keywords: "puzzle" },
      { id: "gacha-ball", label: "Kapsel", keywords: "gacha" },
      { id: "chess-king", label: "Schach König", keywords: "chess" },
      { id: "chess-knight", label: "Schach Springer", keywords: "chess" },
      { id: "chess-pawn", label: "Schach Bauer", keywords: "chess" },
      { id: "chess-queen", label: "Schach Dame", keywords: "chess" },
      { id: "chess-rock", label: "Schach Turm", keywords: "chess" },
      { id: "movie", label: "Film", keywords: "movie" },
      { id: "music", label: "Musik", keywords: "music" },
      { id: "camera", label: "Kamera", keywords: "camera" },
      { id: "guild", label: "Gilde", keywords: "guild wappen" },
      { id: "friend-add", label: "Freunde", keywords: "friend" },
      { id: "chat", label: "Chat", keywords: "chat" },
      { id: "megaphone", label: "Megafon", keywords: "megaphone" },
      { id: "bulb", label: "Idee", keywords: "bulb" },
      { id: "emoji-smile", label: "Lachen", keywords: "smile" },
      { id: "emoji-wow", label: "Staunen", keywords: "wow" },
      { id: "life", label: "Herz", keywords: "heart life" },
      { id: "like", label: "Daumen", keywords: "like" },
      { id: "tv", label: "Fernseher", keywords: "tv" },
      { id: "bell", label: "Glocke", keywords: "bell" },
      { id: "energy", label: "Energie", keywords: "energy" },
      { id: "buff", label: "Stärkung", keywords: "buff" },
    ],
  },
];

export const PICTO_LIST = PICTO_CATEGORIES.flatMap(c => c.icons);
const PICTO_IDS = new Set(PICTO_LIST.map(i => i.id));

export function isPictoId(id: string): boolean {
  return PICTO_IDS.has(id);
}

export function pictoSrc(id: string): string {
  return `/icons/picto/${id}.png`;
}

/** 12 Farben zur Auswahl; die erste ist der Standard. */
export const PICTO_COLORS: { value: string; label: string }[] = [
  { value: "#2dd4bf", label: "Teal" },
  { value: "#b91c1c", label: "Rot" },
  { value: "#f59e0b", label: "Gold" },
  { value: "#f97316", label: "Orange" },
  { value: "#ec4899", label: "Rosa" },
  { value: "#8b5cf6", label: "Violett" },
  { value: "#6366f1", label: "Indigo" },
  { value: "#3b82f6", label: "Blau" },
  { value: "#22d3ee", label: "Cyan" },
  { value: "#22c55e", label: "Grün" },
  { value: "#84cc16", label: "Limette" },
  { value: "#94a3b8", label: "Silber" },
];

export const PICTO_DEFAULT_COLOR = PICTO_COLORS[0].value;
