-- ============================================
-- Battle Cards — neue Tabellen in der OMA-Companion-Supabase-DB
-- ============================================
-- Legt nur neue Objekte an: 5 Enums, 3 Tabellen (Card, UserCard, Battle).
-- Rührt keine bestehende Tabelle an (auch nicht "User").
--
-- Kein separater DB-User nötig: Battle Cards ist inzwischen Teil dieser
-- Next.js-App (siehe src/lib/battle-engine, src/lib/season,
-- src/app/api/battles) und läuft über dieselbe DATABASE_URL/denselben
-- Postgres-User wie der Rest von OMA-Companion.
--
-- Einmalig im Supabase SQL-Editor ausführen (kompletter Block).

-- ---------- 1) Enums ----------

CREATE TYPE "CardClass" AS ENUM ('TANK', 'DAMAGE_DEALER', 'SUPPORT');
CREATE TYPE "CardRarity" AS ENUM ('STANDARD', 'COMMUNITY');
CREATE TYPE "ActivityTier" AS ENUM ('GHOST', 'NPC', 'GAMER', 'LEGENDE', 'OLD_MASTER');
CREATE TYPE "NormalAttackTargetRule" AS ENUM ('LOWEST_DEFENSE', 'HIGHEST_HP', 'LOWEST_HP', 'HIGHEST_ATTACK', 'RANDOM');
CREATE TYPE "BattleResult" AS ENUM ('WIN', 'LOSS', 'DRAW');

-- ---------- 2) Card ----------

CREATE TABLE "Card" (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "class" "CardClass" NOT NULL,
    "rarity" "CardRarity" NOT NULL,
    "flavorText" TEXT NOT NULL,
    "baseHp" INTEGER NOT NULL,
    "baseAttack" INTEGER NOT NULL,
    "baseDefense" INTEGER NOT NULL,
    "speed" INTEGER NOT NULL,
    "normalAttackTargetRule" "NormalAttackTargetRule",
    "passivePositive" JSONB NOT NULL,
    "passiveNegative" JSONB NOT NULL,
    "activeSkill" JSONB NOT NULL,
    "ultimateSkill" JSONB NOT NULL,
    "linkedDiscordId" TEXT,
    "activityTier" "ActivityTier",
    "sourceStatsJson" JSONB,
    "overriddenFields" TEXT[] NOT NULL DEFAULT '{}',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "lastGeneratedAt" TIMESTAMP(3),
    "imageUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE UNIQUE INDEX "Card_linkedDiscordId_key" ON "Card"("linkedDiscordId");

-- ---------- 3) UserCard ----------

CREATE TABLE "UserCard" (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "cardId" TEXT NOT NULL,
    "level" INTEGER NOT NULL DEFAULT 1,
    "duplicates" INTEGER NOT NULL DEFAULT 1,
    "acquiredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UserCard_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"),
    CONSTRAINT "UserCard_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Card"("id")
);

CREATE UNIQUE INDEX "UserCard_userId_cardId_key" ON "UserCard"("userId", "cardId");

-- ---------- 4) Battle ----------

CREATE TABLE "Battle" (
    "id" TEXT PRIMARY KEY,
    "playerId" TEXT NOT NULL,
    "opponentType" TEXT NOT NULL,
    "result" "BattleResult" NOT NULL,
    "teamSnapshot" JSONB NOT NULL,
    "battleLog" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Battle_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "User"("id")
);
