-- ============================================
-- Battle Cards — Setup in der geteilten OMA-Companion-Supabase-DB
-- ============================================
-- Legt NUR neue Objekte an: 5 Enums, 3 Tabellen (Card, UserCard, Battle)
-- und einen eigenen, eingeschränkten DB-User "battlecards_app".
--
-- Rührt KEINE bestehende OMA-Companion-Tabelle an — außer einem lesenden
-- GRANT SELECT auf "User", damit Battle Cards Kartenbesitz prüfen und auf
-- Discord-Mitglieder verlinken kann (Community-Karten).
--
-- WICHTIG: Vor dem Ausführen ganz unten 'CHANGE_ME' durch ein eigenes,
-- starkes Passwort ersetzen. Bestehende Zugangsdaten (der postgres-User,
-- den Vercel/der Discord-Bot nutzt) werden dadurch NICHT verändert — das
-- hier ist ein zusätzlicher, komplett neuer Login.
--
-- Einmalig im Supabase SQL-Editor ausführen (kompletter Block).

-- ---------- 1) Enums ----------

CREATE TYPE "CardClass" AS ENUM ('TANK', 'DAMAGE_DEALER', 'SUPPORT');
CREATE TYPE "CardRarity" AS ENUM ('STANDARD', 'COMMUNITY');
CREATE TYPE "ActivityTier" AS ENUM ('GHOST', 'NPC', 'GAMER', 'LEGENDE', 'OLD_MASTER');
CREATE TYPE "NormalAttackTargetRule" AS ENUM ('LOWEST_DEFENSE', 'HIGHEST_HP', 'LOWEST_HP', 'HIGHEST_ATTACK', 'RANDOM');
CREATE TYPE "BattleResult" AS ENUM ('WIN', 'LOSS', 'DRAW');

-- ---------- 2) Card ----------

CREATE TABLE "Card" (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "class" "CardClass" NOT NULL,
    "rarity" "CardRarity" NOT NULL,
    "flavorText" TEXT NOT NULL,
    "baseHp" INTEGER NOT NULL,
    "baseAttack" INTEGER NOT NULL,
    "baseDefense" INTEGER NOT NULL,
    "speed" INTEGER NOT NULL,
    "normalAttackTargetRule" "NormalAttackTargetRule",
    "passivePositive" JSONB NOT NULL,
    "passiveNegative" JSONB NOT NULL,
    "activeSkill" JSONB NOT NULL,
    "ultimateSkill" JSONB NOT NULL,
    "linkedDiscordId" TEXT,
    "activityTier" "ActivityTier",
    "sourceStatsJson" JSONB,
    "overriddenFields" TEXT[] NOT NULL DEFAULT '{}',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "lastGeneratedAt" TIMESTAMP(3),
    "imageUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE UNIQUE INDEX "Card_linkedDiscordId_key" ON "Card"("linkedDiscordId");

-- ---------- 3) UserCard ----------

CREATE TABLE "UserCard" (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "cardId" TEXT NOT NULL,
    "level" INTEGER NOT NULL DEFAULT 1,
    "duplicates" INTEGER NOT NULL DEFAULT 1,
    "acquiredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UserCard_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"),
    CONSTRAINT "UserCard_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Card"("id")
);

CREATE UNIQUE INDEX "UserCard_userId_cardId_key" ON "UserCard"("userId", "cardId");

-- ---------- 4) Battle ----------

CREATE TABLE "Battle" (
    "id" TEXT PRIMARY KEY,
    "playerId" TEXT NOT NULL,
    "opponentType" TEXT NOT NULL,
    "result" "BattleResult" NOT NULL,
    "teamSnapshot" JSONB NOT NULL,
    "battleLog" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Battle_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "User"("id")
);

-- ---------- 5) Eigener, eingeschränkter DB-User für Battle Cards ----------

CREATE ROLE battlecards_app WITH LOGIN PASSWORD 'CHANGE_ME';

GRANT CONNECT ON DATABASE postgres TO battlecards_app;
GRANT USAGE ON SCHEMA public TO battlecards_app;

-- Nur lesend auf die bestehende, geteilte User-Tabelle
GRANT SELECT ON TABLE "User" TO battlecards_app;

-- Volle Rechte auf die neuen, von Battle Cards verwalteten Tabellen
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "Card", "UserCard", "Battle" TO battlecards_app;
