ALTER TABLE "CollectibleItem" ADD COLUMN IF NOT EXISTS "active"    BOOLEAN   NOT NULL DEFAULT true;
ALTER TABLE "CollectibleItem" ADD COLUMN IF NOT EXISTS "salePrice" INTEGER;
ALTER TABLE "CollectibleItem" ADD COLUMN IF NOT EXISTS "saleUntil" TIMESTAMP(3);
