/**
 * Einmalig auszuführen nach dem Deploy des NotificationRule-Schemas:
 *   npx tsx scripts/seed-notification-rules.ts
 *
 * Upsert aller Notification-Regeln mit Defaults, die dem bisherigen
 * Verhalten entsprechen. Für die 9 Schlüssel, die es schon als BotConfig-
 * Eintrag gibt, wird ein individuell angepasster Text übernommen, falls
 * vorhanden — alles andere bekommt einen neuen sinnvollen Default.
 */
import { prisma } from "@/lib/prisma";

interface RuleSeed {
  key: string;
  label: string;
  description: string;
  category: string;
  pushEnabled: boolean;
  inAppEnabled: boolean;
  discordDmEnabled: boolean;
  discordChanEnabled: boolean;
  titleTemplate: string;
  bodyTemplate: string;
  urlTemplate?: string;
  reminderHoursBefore?: number;
  isEventNotification?: boolean;
  eventAudience?: "all" | "participants";
  /** Schlüssel des alten BotConfig-Eintrags, dessen "{key}_text" übernommen werden soll */
  legacyBotConfigKey?: string;
}

const RULES: RuleSeed[] = [
  {
    key: "event_new",
    label: "Neues Event",
    description: "Wird gesendet, wenn ein neues Event erstellt wird. Titel/Text steuern auch direkt den Discord-Kanal-Embed.",
    category: "events",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "📅 Neues Event: {eventName}",
    bodyTemplate: "Ein neues Community-Event wurde angekündigt! Meldet euch jetzt an.",
    urlTemplate: "/events",
    isEventNotification: true, eventAudience: "all",
    legacyBotConfigKey: "event_new",
  },
  {
    key: "event_reminder",
    label: "Event-Erinnerung",
    description: "Vor Event-Start für alle angemeldeten Nutzer und im Discord-Kanal.",
    category: "events",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "⏰ Bald: {eventName}",
    bodyTemplate: "⏰ Nur noch **weniger als {reminderHours} Stunden** bis **{eventName}** beginnt!\nStart: {date} · Jetzt noch anmelden!",
    urlTemplate: "/events",
    reminderHoursBefore: 24,
    isEventNotification: true, eventAudience: "participants",
    legacyBotConfigKey: "event_reminder",
  },
  {
    key: "event_started",
    label: "Event hat begonnen",
    description: "Wenn ein Discord Scheduled Event auf 'Aktiv' springt.",
    category: "events",
    pushEnabled: true, inAppEnabled: false, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🚀 Event läuft jetzt!",
    bodyTemplate: "🚀 **{eventName}** hat soeben begonnen! Viel Spaß und viel Erfolg! 🎮",
    isEventNotification: true, eventAudience: "participants",
    legacyBotConfigKey: "event_started",
  },
  {
    key: "event_poll_started",
    label: "Umfragephase gestartet",
    description: "Wenn ein Event vom Status 'Aktiv' in die Umfragephase wechselt (Spielphase beendet, Abstimmung läuft).",
    category: "events",
    pushEnabled: true, inAppEnabled: false, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🗳️ Umfrage gestartet: {eventName}",
    bodyTemplate: "🗳️ Die Umfragephase für **{eventName}** hat begonnen — stimmt jetzt ab!",
    isEventNotification: true, eventAudience: "participants",
  },
  {
    key: "event_ended",
    label: "Event beendet",
    description: "Wenn ein Event im Admin-Panel abgeschlossen wird. Titel/Text steuern auch direkt den Discord-Ergebnis-Embed.",
    category: "events",
    pushEnabled: false, inAppEnabled: false, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🏆 Ergebnisse: {eventName}",
    bodyTemplate: "Das Event ist abgeschlossen — die Ergebnisse stehen fest!",
    isEventNotification: true, eventAudience: "participants",
    legacyBotConfigKey: "event_ended",
  },
  {
    key: "quest_completed",
    label: "Quest erfüllt",
    description: "Wenn ein Nutzer eine monatliche Quest abschließt.",
    category: "quests",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: true, discordChanEnabled: false,
    titleTemplate: "⭐ Quest erfüllt: {questTitle}",
    bodyTemplate: "Du erhältst {reward} Münzen!",
    urlTemplate: "/quests",
  },
  {
    key: "quest_new",
    label: "Neue Quests verfügbar",
    description: "Am 1. des Monats, wenn die neuen monatlichen Quests generiert werden.",
    category: "quests",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🎯 Neue Quests für {month}!",
    bodyTemplate: "Die Quests für **{month} {year}** sind da:\n{questTitles}",
    urlTemplate: "/quests",
  },
  {
    key: "prediction_result",
    label: "Vorhersage-Ergebnis",
    description: "Wenn eine Event-Sieger-Vorhersage ausgewertet wurde (richtig oder falsch).",
    category: "tournaments",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎯 Dein Tipp war {result}",
    bodyTemplate: "Du erhältst {reward} Münzen für deine Event-Sieger-Vorhersage.",
    urlTemplate: "/",
  },
  {
    key: "duel_challenge",
    label: "Münzen-Duell-Herausforderung",
    description: "Wenn ein Nutzer zu einem Münzen-Duell herausgefordert wird.",
    category: "tournaments",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⚔️ Duell-Herausforderung",
    bodyTemplate: "{challenger} fordert dich zu einem Münzen-Duell heraus — Einsatz: {wager} Münzen.",
    urlTemplate: "/events?tab=duels",
  },
  {
    key: "duel_result",
    label: "Münzen-Duell-Ergebnis",
    description: "Wenn ein Münzen-Duell aufgelöst wurde.",
    category: "tournaments",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⚔️ Duell-Ergebnis",
    bodyTemplate: "{result}",
    urlTemplate: "/events?tab=duels",
  },
  {
    key: "battle_card_tier_up",
    label: "Battle-Card-Stufenaufstieg",
    description: "Wenn die Aktivitäts-Stufe der eigenen Community-Karte durch eine Saison-Neuberechnung steigt.",
    category: "battle_cards",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🃏 Stufenaufstieg: {tier}",
    bodyTemplate: "Deine Karte „{cardName}\" hat die Aktivitäts-Stufe **{tier}** erreicht!",
    urlTemplate: "/battle-cards/my-card",
  },
  {
    key: "badge_earned",
    label: "System-Abzeichen freigeschaltet",
    description: "Wenn ein Nutzer automatisch ein System-Abzeichen erreicht.",
    category: "badges",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "{badgeIcon} Neues Abzeichen freigeschaltet!",
    bodyTemplate: "„{badgeName}\" — {badgeDesc}",
    urlTemplate: "/profile",
  },
  {
    key: "badge_awarded",
    label: "Abzeichen von Admin vergeben",
    description: "Wenn ein Admin ein individuelles Abzeichen vergibt.",
    category: "badges",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: true, discordChanEnabled: false,
    titleTemplate: "{badgeIcon} Neues Abzeichen erhalten!",
    bodyTemplate: "„{badgeName}\" — {badgeDesc}",
    urlTemplate: "/profile",
  },
  {
    key: "clip_started",
    label: "Clip des Monats – Abstimmung gestartet",
    description: "Wenn ein neuer Clip-Contest erstellt wird.",
    category: "clips",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🎬 Clip des Monats – {month} {year}",
    bodyTemplate: "Die Abstimmung läuft! {nominationCount} Clips stehen zur Wahl.",
    urlTemplate: "/clip-des-monats",
  },
  {
    key: "clip_finished",
    label: "Clip des Monats – Gewinner steht fest",
    description: "Wenn ein Clip-Contest abgeschlossen wird.",
    category: "clips",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🏆 Clip des Monats {month} {year} – {resultHeadline}",
    bodyTemplate: "{resultText}",
    urlTemplate: "/clip-des-monats",
  },
  {
    key: "clip_of_year_started",
    label: "Clip des Jahres – Abstimmung gestartet",
    description: "Wenn die jährliche Clip-des-Jahres-Wahl erstellt wird.",
    category: "clips",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🎬 Clip des Jahres {year}",
    bodyTemplate: "Die Abstimmung läuft! {nominationCount} Clips des Monats stehen zur Wahl.",
    urlTemplate: "/clip-des-jahres",
  },
  {
    key: "clip_of_year_finished",
    label: "Clip des Jahres – Gewinner steht fest",
    description: "Wenn die Clip-des-Jahres-Wahl abgeschlossen wird.",
    category: "clips",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🏆 Clip des Jahres {year} – {resultHeadline}",
    bodyTemplate: "{resultText}",
    urlTemplate: "/clip-des-jahres",
  },
  {
    key: "rank_up",
    label: "Rang-Aufstieg",
    description: "Wenn ein Nutzer durch Aktivität einen neuen Rang erreicht.",
    category: "rank",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "{rankEmoji} Rang-Aufstieg!",
    bodyTemplate: "🎊 {username} hat den Rang **{rank}** erreicht – weiter so!",
    urlTemplate: "/profile",
    legacyBotConfigKey: "rank_up",
  },
  {
    key: "leaderboard",
    label: "Monatliche Rangliste",
    description: "Am 1. des Monats mit den Top-10 des Vormonats.",
    category: "system",
    pushEnabled: false, inAppEnabled: false, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🏆 Monats-Rangliste · {month}",
    bodyTemplate: "🏆 Die aktivsten Mitglieder im **{month}**:\n\n{lines}",
    legacyBotConfigKey: "leaderboard",
  },
  {
    key: "birthday",
    label: "Geburtstag",
    description: "Täglich für Nutzer mit Geburtstag heute.",
    category: "system",
    pushEnabled: false, inAppEnabled: false, discordDmEnabled: false, discordChanEnabled: true,
    titleTemplate: "🎂 Alles Gute zum Geburtstag!",
    bodyTemplate: "🎂 {username} hat heute Geburtstag – alles Gute! 🎉\nAls Geschenk gibt es für die nächsten **24 Stunden** doppelte Punkte!",
    legacyBotConfigKey: "birthday",
  },
  {
    key: "server_approved",
    label: "Server-Bewerbung angenommen",
    description: "Wenn ein Moderator eine Gameserver-Bewerbung annimmt.",
    category: "system",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "Bewerbung angenommen",
    bodyTemplate: "Du hast Zugang zu „{serverName}\" erhalten.",
    urlTemplate: "/servers",
  },
  {
    key: "server_denied",
    label: "Server-Bewerbung abgelehnt",
    description: "Wenn ein Moderator eine Gameserver-Bewerbung ablehnt.",
    category: "system",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "Bewerbung abgelehnt",
    bodyTemplate: "Deine Bewerbung für „{serverName}\" wurde abgelehnt.",
    urlTemplate: "/servers",
  },
  {
    key: "server_revoked",
    label: "Server-Zugriff entzogen",
    description: "Wenn ein Moderator einem Nutzer den Server-Zugriff entzieht.",
    category: "system",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "Zugriff entzogen",
    bodyTemplate: "Dein Zugang zu „{serverName}\" wurde entzogen.",
    urlTemplate: "/servers",
  },
  {
    key: "server_waitlisted",
    label: "Server-Bewerbung auf Warteliste",
    description: "Wenn eine Gameserver-Bewerbung eingereicht wird, der Server aber bereits voll ist.",
    category: "system",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⏳ Auf der Warteliste",
    bodyTemplate: "Du stehst auf der Warteliste für „{serverName}\".",
    urlTemplate: "/servers",
  },
  {
    key: "server_waitlist_promoted",
    label: "Server-Warteliste: Platz frei geworden",
    description: "Wenn ein Slot frei wird und die älteste Warteliste-Bewerbung automatisch zu 'ausstehend' aufrückt.",
    category: "system",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 Ein Platz ist frei geworden",
    bodyTemplate: "Ein Platz auf „{serverName}\" ist frei geworden — deine Bewerbung wird geprüft.",
    urlTemplate: "/servers",
  },
  {
    key: "community_job_approved",
    label: "Community-Job-Bewerbung genehmigt",
    description: "Wenn eine Bewerbung für einen Community-Job genehmigt und sofort aktiv wird.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 Job-Bewerbung genehmigt",
    bodyTemplate: "Du bist jetzt {jobLabel}! Schau in dein Büro im Profil-Reiter „Community-Jobs\".",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_waitlisted",
    label: "Community-Job-Bewerbung auf Warteliste",
    description: "Wenn eine Bewerbung genehmigt wurde, aber alle Slots belegt sind.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⏳ Auf der Warteliste",
    bodyTemplate: "Deine Bewerbung als {jobLabel} wurde genehmigt, aber aktuell sind alle Plätze belegt. Du stehst auf der Warteliste.",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_rejected",
    label: "Community-Job-Bewerbung abgelehnt",
    description: "Wenn eine Bewerbung für einen Community-Job abgelehnt wird.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "Bewerbung abgelehnt",
    bodyTemplate: "Deine Bewerbung als {jobLabel} wurde leider abgelehnt.",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_warned",
    label: "Community-Job-Verwarnung",
    description: "Wenn ein Community-Job-Inhaber verwarnt wird (schlechte Bewertungen oder Inaktivität).",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⚠️ Verwarnung erhalten",
    bodyTemplate: "Du wurdest als {jobLabel} verwarnt: {reason}. Bei anhaltend schlechter Leistung kann dir der Job entzogen werden.",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_revoked",
    label: "Community-Job entzogen",
    description: "Wenn ein Community-Job-Inhaber den Job entzogen bekommt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "Job entzogen",
    bodyTemplate: "Dein Job als {jobLabel} wurde entzogen: {reason}",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_contract_expiring",
    label: "Community-Job-Vertrag läuft bald ab",
    description: "Erinnerung, wenn der Vertrag eines Community-Jobs bald abläuft und noch nicht verlängert wurde.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⏰ Vertrag läuft bald ab",
    bodyTemplate: "Dein Vertrag als {jobLabel} läuft am {contractEndDate} ab. Du kannst ihn jetzt in deinem Büro verlängern.",
    urlTemplate: "/profile",
  },
  {
    key: "coach_session_changed",
    label: "Coach-Termin geändert",
    description: "Wenn ein Coach Titel oder Zeit eines Trainings-Termins ändert — geht an alle angemeldeten Teilnehmer.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎓 Termin geändert: {sessionTitle}",
    bodyTemplate: "{coachName} hat den Termin angepasst. Neuer Beginn: {when}.{note} Du kannst dich in der App ab- oder wieder anmelden.",
    urlTemplate: "/profile",
  },
  {
    key: "coach_session_cancelled",
    label: "Coach-Termin abgesagt",
    description: "Wenn ein Coach einen Trainings-Termin löscht — geht an alle angemeldeten Teilnehmer.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "❌ Termin abgesagt: {sessionTitle}",
    bodyTemplate: "{coachName} hat den Termin am {when} abgesagt.{note}",
    urlTemplate: "/profile",
  },
  {
    key: "coach_session_reminder",
    label: "Coach-Termin Erinnerung",
    description: "Tägliche Erinnerung an angemeldete Teilnehmer (und den Coach) für Trainings, die in den nächsten 24 Stunden beginnen.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⏰ Training bald: {sessionTitle}",
    bodyTemplate: "Beginn {when} bei {coachName}.{meeting}",
    urlTemplate: "/profile",
  },
  {
    key: "coach_waitlist_promoted",
    label: "Coach-Termin: Platz frei geworden",
    description: "Wenn ein Teilnehmer von der Warteliste eines ausgebuchten Trainings automatisch nachrückt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 Du bist dabei: {sessionTitle}",
    bodyTemplate: "Ein Platz ist frei geworden — du bist jetzt für das Training bei {coachName} angemeldet. Beginn: {when}.",
    urlTemplate: "/profile",
  },
  {
    key: "coach_session_summary",
    label: "Coach-Termin: Zusammenfassung",
    description: "Wenn ein Coach nach einem Training eine Zusammenfassung/Tipps an die Teilnehmer schickt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📝 Zusammenfassung: {sessionTitle}",
    bodyTemplate: "{summary}",
    urlTemplate: "/profile",
  },
  {
    key: "coach_help_request",
    label: "Coach: Neue Hilfe-Anfrage",
    description: "Wenn jemand einen Coach um Hilfe bittet (unabhängig von dessen Verfügbarkeit).",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🙋 Hilfe-Anfrage von {requesterName}",
    bodyTemplate: "{message}",
    urlTemplate: "/profile",
  },
  {
    key: "coach_help_answered",
    label: "Coach: Hilfe-Anfrage beantwortet",
    description: "Wenn der Coach eine Hilfe-Anfrage beantwortet.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎓 {coachName} hat geantwortet",
    bodyTemplate: "{reply}",
    urlTemplate: "/community-board",
  },
  {
    key: "coach_welcome",
    label: "Coach: Willkommens-Nachricht",
    description: "Persönliche Willkommens-Nachricht eines Coaches an einen neuen Spieler.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "👋 {coachName} heißt dich willkommen",
    bodyTemplate: "{message}",
    urlTemplate: "/community-board",
  },
  {
    key: "coach_invite",
    label: "Coach: Einladung zum Training",
    description: "Einladung eines Coaches an einen neuen Spieler zu einem Trainings-Termin.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎓 Einladung: {sessionTitle}",
    bodyTemplate: "{coachName} lädt dich zum Training ein — Beginn {when}. Du kannst dich in der App anmelden.",
    urlTemplate: "/profile",
  },
  {
    key: "report_contribution",
    label: "Bericht ergänzt",
    description: "Wenn ein anderer Journalist deinen Bericht ergänzt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "✍️ {authorName} hat deinen Bericht ergänzt",
    bodyTemplate: "Zu „{title}“ gibt es eine neue Ergänzung.",
    urlTemplate: "{url}",
  },
  {
    key: "report_comment",
    label: "Bericht kommentiert",
    description: "Wenn jemand deinen Bericht im Community-Board kommentiert.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "💬 Neuer Kommentar zu „{title}“",
    bodyTemplate: "{authorName}: {excerpt}",
    urlTemplate: "{url}",
  },
  {
    key: "report_votes_milestone",
    label: "Bericht: Daumen-Meilenstein",
    description: "Wenn ein eigener Bericht 5/10/25/50/100 Daumen erreicht.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 {count} Daumen für „{title}“",
    bodyTemplate: "Dein Bericht kommt richtig gut an!",
    urlTemplate: "{url}",
  },
  {
    key: "asset_used",
    label: "Dein Bild wurde verwendet",
    description: "Wenn ein Journalist dein Bild als Titelbild oder ein Marketing Manager es in einem Post nutzt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📸 Dein Bild wird verwendet",
    bodyTemplate: "{user} nutzt dein Bild: {title}",
    urlTemplate: "{url}",
  },
  {
    key: "asset_votes_milestone",
    label: "Bild: Daumen-Meilenstein",
    description: "Wenn ein eigenes Bild/Clip 5/10/25/50/100 Daumen erreicht.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 {count} Daumen für dein Bild",
    bodyTemplate: "„{title}“ kommt richtig gut an!",
    urlTemplate: "{url}",
  },
  {
    key: "marketing_votes_milestone",
    label: "Werbe-Post: Daumen-Meilenstein",
    description: "Wenn ein eigener Werbe-Post 5/10/25/50/100 Daumen erreicht.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 {count} Daumen für deinen Werbe-Post",
    bodyTemplate: "{title}",
    urlTemplate: "{url}",
  },
  {
    key: "marketing_post_confirmed",
    label: "Werbe-Post extern bestätigt",
    description: "Wenn ein Admin bestätigt, dass dein Werbe-Post extern (z.B. Instagram) veröffentlicht wurde.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "✅ Dein Post wurde extern veröffentlicht",
    bodyTemplate: "{title}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_vote",
    label: "Idee: neue Bewertung",
    description: "Wenn jemand deine Idee bewertet.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⭐ {stars} Sterne für deine Idee",
    bodyTemplate: "{title}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_votes_milestone",
    label: "Idee: Stimmen-Meilenstein",
    description: "Wenn eine eigene Idee 5/10/25/50/100 Bewertungen erreicht.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 {count} Bewertungen für „{title}“",
    bodyTemplate: "Durchschnitt: {average} Sterne",
    urlTemplate: "{url}",
  },
  {
    key: "idea_comment",
    label: "Idee: neuer Kommentar",
    description: "Wenn jemand deine Idee kommentiert.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "💬 {authorName} kommentiert deine Idee",
    bodyTemplate: "{excerpt}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_status",
    label: "Idee: neuer Status",
    description: "Wenn das Team den Status deiner Idee ändert (in Prüfung, umgesetzt, abgelehnt …).",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "{status} – „{title}“",
    bodyTemplate: "{note}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_voting_ended",
    label: "Idee: Abstimmung beendet",
    description: "Zusammenfassung, wenn die Abstimmungsfrist deiner Idee abgelaufen ist.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "⏱️ Abstimmung beendet: „{title}“",
    bodyTemplate: "{count} Bewertungen, Durchschnitt {average} Sterne",
    urlTemplate: "{url}",
  },
  {
    key: "idea_interest",
    label: "Idee: Interesse",
    description: "Wenn jemand bei deiner Idee mitmachen oder helfen möchte.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🙋 {name} {kind}",
    bodyTemplate: "{title}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_revised",
    label: "Idee überarbeitet",
    description: "Wenn eine Idee, die du bewertet hast, überarbeitet wurde — du kannst neu bewerten.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "✏️ Idee überarbeitet: „{title}“",
    bodyTemplate: "{note}",
    urlTemplate: "{url}",
  },
  {
    key: "idea_mention",
    label: "In Idee erwähnt",
    description: "Wenn du in einer Idee erwähnt wirst.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "💡 {authorName} hat dich in einer Idee erwähnt",
    bodyTemplate: "{title}",
    urlTemplate: "{url}",
  },
  {
    key: "community_content_hidden",
    label: "Beitrag ausgeblendet",
    description: "Wenn ein Team-Mitglied einen deiner Community-Job-Beiträge ausblendet.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🚫 Beitrag ausgeblendet",
    bodyTemplate: "„{title}“ wurde vom Team ausgeblendet. Grund: {reason}",
    urlTemplate: "/profile",
  },
  {
    key: "community_content_restored",
    label: "Beitrag wieder sichtbar",
    description: "Wenn ein ausgeblendeter Beitrag wieder eingeblendet wird.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "✅ Beitrag wieder sichtbar",
    bodyTemplate: "„{title}“ ist wieder für alle sichtbar.",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_contract_adjusted",
    label: "Vertrag angepasst",
    description: "Wenn das Team dein Vertragsende ändert.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📅 Vertrag angepasst",
    bodyTemplate: "Dein Vertrag als {jobLabel} läuft jetzt bis {date}. {reason}",
    urlTemplate: "/profile",
  },
  {
    key: "promotion_request",
    label: "Werbe-Anfrage",
    description: "Ein Coach bittet die Marketing Manager, einen Trainings-Termin zu bewerben.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📣 Werbe-Anfrage von {requesterName}",
    bodyTemplate: "{title} ({date})",
    urlTemplate: "/profile",
  },
  {
    key: "promotion_fulfilled",
    label: "Werbe-Anfrage erfüllt",
    description: "Ein Marketing Manager hat einen Werbe-Post zu deinem Training erstellt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "✅ Dein Training wird beworben",
    bodyTemplate: "{title}",
    urlTemplate: "/profile",
  },
  {
    key: "report_mention",
    label: "In Bericht erwähnt",
    description: "Wenn du in einem Bericht oder einer Ergänzung erwähnt wirst.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📰 {authorName} hat dich erwähnt",
    bodyTemplate: "In „{title}“ wirst du genannt.",
    urlTemplate: "{url}",
  },
  {
    key: "photo_request",
    label: "Bildwunsch",
    description: "Ein Community-Job-Mitglied (Journalist, Marketing Manager, Coach, Visionär) bittet die Fotografen um ein Bild.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📸 Bildwunsch von {requesterName}",
    bodyTemplate: "{eventTitle}: {description}",
    urlTemplate: "/profile",
  },
  {
    key: "photo_request_fulfilled",
    label: "Bildwunsch erfüllt",
    description: "Ein Fotograf hat deinen Bildwunsch erfüllt.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "📸 Dein Bildwunsch wurde erfüllt",
    bodyTemplate: "{fotografName} hat ein Bild hochgeladen — du findest es in der Mediathek.",
    urlTemplate: "/profile",
  },
  {
    key: "interview_request",
    label: "Interview-Anfrage",
    description: "Ein Journalist bittet dich um ein Interview.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎤 Interview-Anfrage von {journalistName}",
    bodyTemplate: "Du hast Fragen zu beantworten — das dauert nur ein paar Minuten.",
    urlTemplate: "/interviews/{interviewId}",
  },
  {
    key: "interview_answered",
    label: "Interview beantwortet",
    description: "Dein Interview wurde beantwortet.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎤 {intervieweeName} hat geantwortet",
    bodyTemplate: "Die Antworten stehen in deinem Büro zum Einfügen in einen Bericht bereit.",
    urlTemplate: "/profile",
  },
  {
    key: "community_job_handoff_received",
    label: "Community-Job übernommen",
    description: "Wenn ein Job per Übergabe (freiwillig oder durch Admin) an einen Bewerber übergeben wird.",
    category: "community_jobs",
    pushEnabled: true, inAppEnabled: true, discordDmEnabled: false, discordChanEnabled: false,
    titleTemplate: "🎉 Job übernommen",
    bodyTemplate: "Du hast den Job {jobLabel} übernommen! Schau in dein Büro im Profil-Reiter „Community-Jobs\".",
    urlTemplate: "/profile",
  },
];

async function main() {
  const legacyConfig = Object.fromEntries(
    (await prisma.botConfig.findMany()).map((r) => [r.key, r.value]),
  );

  for (const rule of RULES) {
    const legacyText = rule.legacyBotConfigKey
      ? legacyConfig[`${rule.legacyBotConfigKey}_text`]
      : undefined;
    const legacyEnabled = rule.legacyBotConfigKey
      ? legacyConfig[`${rule.legacyBotConfigKey}_enabled`]
      : undefined;

    const bodyTemplate = legacyText ?? rule.bodyTemplate;
    const discordChanEnabled = legacyEnabled !== undefined
      ? legacyEnabled === "true"
      : rule.discordChanEnabled;

    await prisma.notificationRule.upsert({
      where: { key: rule.key },
      create: {
        key: rule.key,
        label: rule.label,
        description: rule.description,
        category: rule.category,
        pushEnabled: rule.pushEnabled,
        inAppEnabled: rule.inAppEnabled,
        discordDmEnabled: rule.discordDmEnabled,
        discordChanEnabled,
        titleTemplate: rule.titleTemplate,
        bodyTemplate,
        urlTemplate: rule.urlTemplate ?? null,
        reminderHoursBefore: rule.reminderHoursBefore ?? null,
        isEventNotification: rule.isEventNotification ?? false,
        eventAudience: rule.eventAudience ?? "all",
      },
      update: {}, // Bereits vorhandene Regeln nicht überschreiben (idempotent bei erneutem Lauf)
    });
    console.log(`✓ ${rule.key}${legacyText ? " (Text aus BotConfig übernommen)" : ""}`);
  }

  console.log(`\n${RULES.length} Notification-Regeln geseedet.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
