// ============================================
// Community-Karten — Cold Start für neue Mitglieder
// ============================================
// Legt für ein brandneues OMA-Mitglied (noch ohne jede Aktivitäts-Historie)
// eine erste Community-Karte + UserCard an. Getrennt von runSeasonUpdate()
// in apply-season-results.ts, weil dort explizit vorausgesetzt wird, dass
// die Karte schon existiert ("Keine Karte für User X gefunden — überspringe").
//
// Seit dem D&D-Weltkarten-Feature ist die erste Karte eines Mitglieds direkt
// ein vollständiger, ausgewürfelter D&D-Charakter (Rasse/Klasse/Attribute/
// Backstory, siehe src/lib/dnd/character-creation.ts) statt eines TANK-
// Platzhalters — der bisherige "Kalter Start"-Lückenschluss aus
// PROJECT_CONTEXT.md Offene Punkte #6 bleibt (idempotent, Race-Condition-
// sicher), nur der Inhalt der angelegten Karte hat sich geändert. Klasse/
// Stats/Rasse landen sofort in overriddenFields — runSeasonUpdate() fasst sie
// danach nie wieder an (siehe apply-season-results.ts).

import { Prisma, type Card } from "@prisma/client";
import { prisma } from "../prisma";
import { getSkillTemplate } from "../battle-cards/skill-templates";
import { rollNewCharacterSheet, withDndOverriddenFields } from "../dnd/character-creation";
import { ensureDndWorldSeeded, START_LOCATION_SLUG } from "../dnd/locations";

export interface NewCommunityMemberInput {
  userId: string;
  discordId: string;
  displayName: string;
}

export interface EnsureCommunityCardResult {
  created: boolean;
  card: Card;
}

function toJson<T>(value: T): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value));
}

/**
 * Idempotent: Falls für diese discordId schon eine Karte existiert
 * (Unique-Constraint auf Card.linkedDiscordId), wird nichts verändert.
 */
export async function ensureCommunityCard(
  member: NewCommunityMemberInput
): Promise<EnsureCommunityCardResult> {
  const existing = await prisma.card.findUnique({
    where: { linkedDiscordId: member.discordId },
  });
  if (existing) return { created: false, card: existing };

  await ensureDndWorldSeeded();
  const startLocation = await prisma.dndLocation.findUnique({ where: { slug: START_LOCATION_SLUG } });

  const sheet = rollNewCharacterSheet(member.displayName, "male", Math.random);
  const template = getSkillTemplate(sheet.cardClass, member.discordId);

  try {
    const card = await prisma.$transaction(async (tx) => {
      const created = await tx.card.create({
        data: {
          name: member.displayName,
          // Bewusst leer statt Klassen-Platzhalter ("Tank" etc.) — Untertitel/
          // Beschreibung sind persönlich, bleiben leer, bis Admin oder das
          // Mitglied selbst etwas einträgt (siehe lib/battle-cards/card-content.ts).
          title: "",
          class: sheet.cardClass,
          rarity: "COMMUNITY",
          flavorText: "",
          baseHp: sheet.derivedStats.baseHp,
          baseAttack: sheet.derivedStats.baseAttack,
          baseDefense: sheet.derivedStats.baseDefense,
          speed: sheet.derivedStats.speed,
          normalAttackTargetRule: template.normalAttackTargetRule,
          passivePositive: toJson(template.passivePositive),
          passiveNegative: toJson(template.passiveNegative),
          activeSkill: toJson(template.activeSkill),
          ultimateSkill: toJson(template.ultimateSkill),
          linkedDiscordId: member.discordId,
          activityTier: "GHOST",
          isAutoGenerated: true,
          lastGeneratedAt: new Date(),
          dndRace: sheet.race.name,
          dndClass: sheet.dndClass.name,
          abilityScores: toJson(sheet.abilityScores),
          backstory: sheet.backstory,
          dndCreatedAt: new Date(),
          currentLocationId: startLocation?.id,
          overriddenFields: withDndOverriddenFields([]),
        },
      });

      await tx.userCard.create({
        data: { userId: member.userId, cardId: created.id, level: 1, duplicates: 1 },
      });

      return created;
    });

    return { created: true, card };
  } catch (error) {
    // Race condition: zwei parallele Webhook-Aufrufe für denselben User.
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      const card = await prisma.card.findUniqueOrThrow({
        where: { linkedDiscordId: member.discordId },
      });
      return { created: false, card };
    }
    throw error;
  }
}
