// ============================================
// Community-Karten — Cold Start für neue Mitglieder
// ============================================
// Legt für ein brandneues OMA-Mitglied (noch ohne jede Aktivitäts-Historie)
// eine erste Community-Karte + UserCard an. Getrennt von runSeasonUpdate()
// in apply-season-results.ts, weil dort explizit vorausgesetzt wird, dass
// die Karte schon existiert ("Keine Karte für User X gefunden — überspringe").
//
// Diese Datei füllt genau die Lücke aus PROJECT_CONTEXT.md Offene Punkte #6
// ("Kalter Start der Community-Karten ... Fallback-Logik für die
// Erstzuordnung fehlt"). Klasse/Titel/Skills sind hier bewusst simple,
// klar gekennzeichnete Platzhalter — der nächste echte Saison-Lauf
// (runSeasonUpdate) berechnet Klasse + Aktivitäts-Stufe sauber über die
// echten Perzentile und überschreibt sie wieder (außer bei manuellem
// Override über overriddenFields).

import { Prisma, type Card, type CardClass } from "@prisma/client";
import { CLASS_BASE_STATS } from "./apply-season-results";
import { TIER_MULTIPLIER } from "./season-engine";
import { prisma } from "../prisma";
import { STANDARD_CARDS } from "../../../prisma/battle-cards-seed-data";

export interface NewCommunityMemberInput {
  userId: string;
  discordId: string;
  displayName: string;
}

export interface EnsureCommunityCardResult {
  created: boolean;
  card: Card;
}

// Cold Start: ohne jede Aktivitäts-Historie ist eine echte Perzentil-basierte
// Klassenzuordnung (siehe resolveClass() in season-engine.ts) nicht sinnvoll
// möglich — alle drei Säulen stünden bei 0. TANK ist hier eine willkürliche,
// aber deterministische Wahl (nicht Teil des dokumentierten Konzepts).
const COLD_START_CLASS: CardClass = "TANK";

// Platzhalter-Skills fürs Cold-Start-Erscheinungsbild: geliehen von der
// thematisch nächsten Standard-Karte derselben Klasse. Community-Karten
// haben laut Kontext-Dokument keine eigenen dokumentierten Skills — bis das
// entschieden ist, ist "geliehen" besser als leer oder erfunden.
const SKILL_TEMPLATE_CARD_BY_CLASS: Record<CardClass, string> = {
  TANK: "Bastionella",
  DAMAGE_DEALER: "Scherbe",
  SUPPORT: "Pflästerchen",
};

const CLASS_PLACEHOLDER_TITLE: Record<CardClass, string> = {
  TANK: "Tank",
  DAMAGE_DEALER: "Damage Dealer",
  SUPPORT: "Support",
};

// Mittelwert der dokumentierten Speed-Spanne je Klasse (Tank 40-55, Support
// 55-70, Damage Dealer 75-90). Speed ist laut Schema "fix pro Karte" — wird
// hier einmalig gesetzt und danach nie wieder verändert (auch nicht von
// runSeasonUpdate).
const CLASS_SPEED_MIDPOINT: Record<CardClass, number> = {
  TANK: 47,
  SUPPORT: 62,
  DAMAGE_DEALER: 82,
};

function toJson<T>(value: T): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value));
}

/**
 * Idempotent: Falls für diese discordId schon eine Karte existiert
 * (Unique-Constraint auf Card.linkedDiscordId), wird nichts verändert.
 */
export async function ensureCommunityCard(
  member: NewCommunityMemberInput
): Promise<EnsureCommunityCardResult> {
  const existing = await prisma.card.findUnique({
    where: { linkedDiscordId: member.discordId },
  });
  if (existing) return { created: false, card: existing };

  const cls = COLD_START_CLASS;
  const baseStats = CLASS_BASE_STATS[cls];
  const multiplier = TIER_MULTIPLIER.GHOST;
  const template = STANDARD_CARDS.find(
    (c) => c.name === SKILL_TEMPLATE_CARD_BY_CLASS[cls]
  )!;

  try {
    const card = await prisma.card.create({
      data: {
        name: member.displayName,
        title: CLASS_PLACEHOLDER_TITLE[cls],
        class: cls,
        rarity: "COMMUNITY",
        flavorText: "",
        baseHp: Math.round(baseStats.hp * multiplier),
        baseAttack: Math.round(baseStats.attack * multiplier),
        baseDefense: Math.round(baseStats.defense * multiplier),
        speed: CLASS_SPEED_MIDPOINT[cls],
        passivePositive: toJson(template.passivePositive),
        passiveNegative: toJson(template.passiveNegative),
        activeSkill: toJson(template.activeSkill),
        ultimateSkill: toJson(template.ultimateSkill),
        linkedDiscordId: member.discordId,
        activityTier: "GHOST",
        isAutoGenerated: true,
        lastGeneratedAt: new Date(),
      },
    });

    await prisma.userCard.create({
      data: { userId: member.userId, cardId: card.id, level: 1, duplicates: 1 },
    });

    return { created: true, card };
  } catch (error) {
    // Race condition: zwei parallele Webhook-Aufrufe für denselben User.
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      const card = await prisma.card.findUniqueOrThrow({
        where: { linkedDiscordId: member.discordId },
      });
      return { created: false, card };
    }
    throw error;
  }
}
