// ============================================
// Community-Karten — Cold Start für neue Mitglieder
// ============================================
// Legt für ein brandneues OMA-Mitglied (noch ohne jede Aktivitäts-Historie)
// eine erste Community-Karte + UserCard an. Getrennt von runSeasonUpdate()
// in apply-season-results.ts, weil dort explizit vorausgesetzt wird, dass
// die Karte schon existiert ("Keine Karte für User X gefunden — überspringe").
//
// Diese Datei füllt genau die Lücke aus PROJECT_CONTEXT.md Offene Punkte #6
// ("Kalter Start der Community-Karten ... Fallback-Logik für die
// Erstzuordnung fehlt"). Klasse/Titel/Skills sind hier bewusst simple,
// klar gekennzeichnete Platzhalter — der nächste echte Saison-Lauf
// (runSeasonUpdate) berechnet Klasse + Aktivitäts-Stufe sauber über die
// echten Perzentile und überschreibt sie wieder (außer bei manuellem
// Override über overriddenFields).

import { Prisma, type Card, type CardClass } from "@prisma/client";
import { CLASS_BASE_STATS } from "./apply-season-results";
import { TIER_MULTIPLIER } from "./season-engine";
import { prisma } from "../prisma";
import { getSkillTemplate } from "../battle-cards/skill-templates";

export interface NewCommunityMemberInput {
  userId: string;
  discordId: string;
  displayName: string;
}

export interface EnsureCommunityCardResult {
  created: boolean;
  card: Card;
}

// Cold Start: ohne jede Aktivitäts-Historie ist eine echte Perzentil-basierte
// Klassenzuordnung (siehe resolveClass() in season-engine.ts) nicht sinnvoll
// möglich — alle drei Säulen stünden bei 0. TANK ist hier eine willkürliche,
// aber deterministische Wahl (nicht Teil des dokumentierten Konzepts).
const COLD_START_CLASS: CardClass = "TANK";

// Mittelwert der dokumentierten Speed-Spanne je Klasse (Tank 40-55, Support
// 55-70, Damage Dealer 75-90). Speed ist laut Schema "fix pro Karte" — wird
// hier einmalig gesetzt und danach nie wieder verändert (auch nicht von
// runSeasonUpdate).
const CLASS_SPEED_MIDPOINT: Record<CardClass, number> = {
  TANK: 47,
  SUPPORT: 62,
  DAMAGE_DEALER: 82,
};

function toJson<T>(value: T): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value));
}

/**
 * Idempotent: Falls für diese discordId schon eine Karte existiert
 * (Unique-Constraint auf Card.linkedDiscordId), wird nichts verändert.
 */
export async function ensureCommunityCard(
  member: NewCommunityMemberInput
): Promise<EnsureCommunityCardResult> {
  const existing = await prisma.card.findUnique({
    where: { linkedDiscordId: member.discordId },
  });
  if (existing) return { created: false, card: existing };

  const cls = COLD_START_CLASS;
  const baseStats = CLASS_BASE_STATS[cls];
  const multiplier = TIER_MULTIPLIER.GHOST;
  const template = getSkillTemplate(cls, member.discordId);

  try {
    const card = await prisma.$transaction(async (tx) => {
      const created = await tx.card.create({
        data: {
          name: member.displayName,
          // Bewusst leer statt Klassen-Platzhalter ("Tank" etc.) — Untertitel/
          // Beschreibung sind persönlich, bleiben leer, bis Admin oder das
          // Mitglied selbst etwas einträgt (siehe lib/battle-cards/card-content.ts).
          title: "",
          class: cls,
          rarity: "COMMUNITY",
          flavorText: "",
          baseHp: Math.round(baseStats.hp * multiplier),
          baseAttack: Math.round(baseStats.attack * multiplier),
          baseDefense: Math.round(baseStats.defense * multiplier),
          speed: CLASS_SPEED_MIDPOINT[cls],
          normalAttackTargetRule: template.normalAttackTargetRule,
          passivePositive: toJson(template.passivePositive),
          passiveNegative: toJson(template.passiveNegative),
          activeSkill: toJson(template.activeSkill),
          ultimateSkill: toJson(template.ultimateSkill),
          linkedDiscordId: member.discordId,
          activityTier: "GHOST",
          isAutoGenerated: true,
          lastGeneratedAt: new Date(),
        },
      });

      await tx.userCard.create({
        data: { userId: member.userId, cardId: created.id, level: 1, duplicates: 1 },
      });

      return created;
    });

    return { created: true, card };
  } catch (error) {
    // Race condition: zwei parallele Webhook-Aufrufe für denselben User.
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      const card = await prisma.card.findUniqueOrThrow({
        where: { linkedDiscordId: member.discordId },
      });
      return { created: false, card };
    }
    throw error;
  }
}
